baseurl = "https://maiyeuminhem123.github.io/my-hugo-blog-/"
languageCode = "vi"
theme = "hugo-theme-stack"
title = "Blog Láº­p TrÃ¬nh Java & JavaScript"
copyright = "Nguyá»…n VÄƒn Thuáº­n"
DefaultContentLanguage = "vi"
hasCJKLanguage = true

[services]
  [services.disqus]
    shortname = "hugo-theme-stack"
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 3

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = ""
  
  # Layout improvements - wider content
  listPageSize = 8
  listPageSizeInArchive = 16
  
  # Content width optimization
  contentWidth = "wide"

  [params.footer]
    since = 2024
    customText = "Blog Láº­p TrÃ¬nh Java & JavaScript - Äá»“ Ã¡n há»c pháº§n"

  [params.dateFormat]
    published = "02/01/2006"
    lastUpdated = "02/01/2006 15:04"

  [params.sidebar]
    emoji = "ğŸš€"
    subtitle = "Blog cÃ¡ nhÃ¢n chia sáº» kiáº¿n thá»©c láº­p trÃ¬nh Java & JavaScript"
    width = "260px"
    sticky = true
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "images/avatar.png"

  [params.article]
    math = false
    toc = true
    readingTime = true
    showWordCount = true
    showReadingTime = true
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
    enabled = true
    provider = "disqus"

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.imageProcessing.cover]
    enabled = true
  [params.imageProcessing.content]
    enabled = true

[params.assets]
  favicon = "/favicon.ico"
  avatar = "images/avatar.png"

[menu]
  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/maiyeuminhem123"
    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    identifier = "email"
    name = "Email"
    url = "mailto:nguyenvanthuan7395@gmail.com"
    [menu.social.params]
      icon = "mail"
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Giá»›i thiá»‡u"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3
  [[menu.main]]
    name = "LiÃªn há»‡"
    url = "/contact/"
    weight = 4

[related]
  includeNewer = true
  threshold = 60
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 200

[markup]
  [markup.goldmark.extensions.passthrough]
    enable = true
    block = [["\\[", "\\]"], ["$$", "$$"]]
    inline = [["\\(", "\\)"]]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4

[languages]
  [languages.en]
    languageName = "English"
    title = "Example Site"
    weight = 1
    [languages.en.params.sidebar]
      subtitle = "Example description"
      [languages.en.params.sidebar.avatar]
        enabled = true
        local = false
        src = "/images/avatar.png"

  [languages.zh-cn]
    languageName = "ä¸­æ–‡"
    title = "æ¼”ç¤ºç«™ç‚¹"
    weight = 2
    [languages.zh-cn.params.sidebar]
      subtitle = "æ¼”ç¤ºè¯´æ˜"
      [languages.zh-cn.params.sidebar.avatar]
        enabled = true
        local = false
        src = "/images/avatar.png"

  [languages.ar]
    languageName = "Ø¹Ø±Ø¨ÙŠ"
    languagedirection = "rtl"
    title = "Ù…ÙˆÙ‚Ø¹ ØªØ¬Ø±ÙŠØ¨ÙŠ"
    weight = 3
    [languages.ar.params.sidebar]
      subtitle = "ÙˆØµÙ ØªØ¬Ø±ÙŠØ¨ÙŠ"
      [languages.ar.params.sidebar.avatar]
        enabled = true
        local = false
        src = "/images/avatar.png"

  [languages.vi]
    languageName = "Tiáº¿ng Viá»‡t"
    title = "Blog Láº­p TrÃ¬nh Java & JavaScript"
    weight = 0
    languageCode = "vi"
    [languages.vi.params.sidebar]
      subtitle = "Blog cÃ¡ nhÃ¢n chia sáº» kiáº¿n thá»©c láº­p trÃ¬nh Java & JavaScript"
      [languages.vi.params.sidebar.avatar]
        enabled = true
        local = false
        src = "/images/avatar.png"
